### ISSUE TITLE
PHP and MySQL Data Source Request?

### ISSUE THREAD

**Issue by flashmaster82** [1rosehip/jplist-es6#19] opened 2018-08-23 20:37 UTC
Is it possible to request data using PHP/Mysql as in previous version, or should we use the old version? If not what do you think it´s best "plugin" for that type of listening? /thanks

**Comment by flashmaster82** [comment] 2018-08-23 20:38
Is it possible to request data using PHP/Mysql as in previous version?

**Comment by 1rosehip** [comment] 2018-08-24 06:15
Duplicate of #18

**Closed by 1rosehip** 2018-08-24 06:15 UTC
